version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=roiadmin
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=bank
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=roiadmin
    depends_on:
      - db


