# Generated by Django 4.1 on 2022-08-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование банка')),
                ('term_min', models.PositiveIntegerField(verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.PositiveIntegerField(verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(verbose_name='Ставка, ДО')),
                ('payment_min', models.PositiveIntegerField(verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.PositiveIntegerField(verbose_name='Сумма кредита, ДО')),
            ],
        ),
    ]
